name: dragon ball wf
on: push
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: Test File exists
        run: ls

  second_test_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: Test File exists
        run: ls

  deploy-job:
    needs: [second_test_job, test_job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: Read File
        run: cat dragon.txt

      - name: checkout repo files
        run: ls