name: dragon ball wf
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout  # Added a space after the hyphen
        uses: actions/checkout@v4.1.7

      -name: welcome msg  # Added a space after the hyphen
        run: echo "hello dragoon"

      -name: xxx  # Added a space after the hyphen
        run: |
          chmod +x ./script.sh 
          ./script.sh

      -name: run dragon script  # Added a space after the hyphen and fixed the duplicate "run"
        run: |
          chmod +x ./scriptdragon.sh
          ./scriptdragon.sh
