name: dragon ball wf
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    -name: welcome msg
    run: echo "hello dragoon"

    -name: xxx
    run: 
          |
          chmod +x ./script.sh 
          ./script.sh
    run:
        |
        chmod +x ./scriptdragon.sh
        ./scriptdragon.sh
