name: dragon ball wf
on: push
jobs:
  test_job:
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dragon-file

      - name: Test File exists
        run: ls

  
  test_job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dragon-file
      
      - name: Test File exists
        run: ls

  deploy-job:
    needs: [test_job, first-job]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dragon-file

      - name: Read File
        run: cat dragon.txt

      - name: checkout repo files
        run: ls